### ISSUE TITLE
Why is cov(X-mean) != cov(X) ?

### ISSUE THREAD

**Issue by Emmak02** [datascience-mobi/2021-topic-04-team-02#1]
The covariance is calculated by: 
![cov](https://user-images.githubusercontent.com/82159105/122357210-d227f000-cf53-11eb-8af4-ef6e3b4e5001.JPG)
(taken from slide 116 of Bioinfo lecture)
so if i give a covariance function a matrix where the mean has already been subtracted it should give the same result as without subtracting the mean because the new mean of (X-mean) should be 0. And therefore I've done the same operations on each entry in either case.
But I've tried it in 'Data exploration.ipynb' both with a 3x3 matrix and with our data and it's not the same. (I can't seem to reference the exact line so here's a screenshot. You can find my madness at the bottom of the file. I tried quite a few things so you'll have to take out the #s and replace the np.corrcoef with np.cov for the 3x3 matrices.)
![code](https://user-images.githubusercontent.com/82159105/122356899-84ab8300-cf53-11eb-9cfd-af704a53f76d.JPG)
@npeschke What am I not understanding?

**Comment by npeschke** [comment]
For the future, please provide examples which can be run directly without source code modification. Not only does that make it quicker for the person trying to help, it also is more reproducible.

This is a working minimum example that demonstrates that the subtraction of the mean does not matter.
```python
import numpy as np
mat = np.array([[0, 1, 2],
                [2, 1, 0]])

mat_cov = np.cov(mat)
mat_cov_mean = np.cov(mat - np.mean(mat))

print(np.array_equal(mat_cov, mat_cov_mean))

>>> True
```

As both matrices are in fact equal.


> I tried quite a few things so you'll have to take out the #s and replace the np.corrcoef with np.cov for the 3x3 matrices.

If you follow those instructions the result is the same.

**Comment by Emmak02** [comment]
Thanks for the reply and sorry for the bad formatting.
I found the error in my 3x3 example: I forgot to specify the axis of the mean... 

However could you explain why it's different for the training data?
![code1](https://user-images.githubusercontent.com/82159105/122960442-b1accb00-d383-11eb-9f6e-a39fbeb747f1.JPG)
