### ISSUE TITLE
Unwanted error message(s)

### ISSUE THREAD

**Issue by Emmak02** [datascience-mobi/2021-topic-04-team-02#2]
Hi @npeschke 
```python
import numpy as np
from functions.Standardize import center

m1 = np.array([[1,2,10],[1,3,2],[1,6,5]])
m2 = np.array([[1,2,5],[1,7,9],[1,2,3]])

center(m1, m2, scale=True)
```
My function works how I want it to but it gives these ugly error messages:
1. " FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if Y == "None": "
2. " RuntimeWarning: invalid value encountered in true_divide
  c_mat = c_mat / std_dev[:, None] "

Is there a way I can tell python not to print these error messages? 
Especially the second one is unavoidable so it would be nicer if it didn't print it every time...

**Comment by npeschke** [comment]
Can you explain why they are happening?
If you can, there should be a way to circumvent them.

**Comment by Emmak02** [comment]
The second one happens because I divide by zero if the standard deviation is 0. The result is a 'nan' for that particular entry, which is something I want to have because I can then 'select' all the nan values immediately after. Is there a way to still get the nan values without it printing the error message?

**Comment by npeschke** [comment]
since you know why the warning is raised and explicitly want the behavior, 
you can ignore the warning for the specific lines of code

```python
with np.errstate(divide='ignore'):
    # some code here
```
https://stackoverflow.com/a/29950752/12416400
